--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/adeynes/cucumber
branches:
- master
- stable

projects:
  cucumber:
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.1.1
      - src: adeynes/parsecmd/parsecmd
        version: ^4.0.0
      - src: adeynes/asyncio/asyncio
        version: ^0.1.0
...
