--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/adeynes/cucumber
branches:
- master
- stable

projects:
  cucumber:
    icon: icon.jpg
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.1.1
      - src: adeynes/parsecmd/parsecmd
        version: ^3.1.0
...
