--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/adeynes/cucumber
branches:
- master

projects:
  cucumber:
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.1.1
      - src: adeynes/parsecmd/parsecmd
        version: ^1.0.0
...
