name: cucumber
main: cucumber\Cucumber
version: 0.1.0
api: 3.0.0
load: POSTWORLD
author: alexisdeynes
description: Advanced, flexible moderation plugin
website: https://github.com/adeynes

commands:
  rawtell:
    description: 'Send a raw message to a player'
    usage: '/rawtell <player> <message> [-m] [-p] [-t]'
    permission: cucumber.command.rawtell

  log:
    description: 'Log a message'
    usage: '/log <message> [level]'
    permission: cucumber.command.log

  alert:
    description: 'Broadcast a message to the server'
    usage: '/alert <message> [-m] [-p] [-t]'
    permission: cucumber.command.alert

  mute:
    description: 'Mute a player'
    usage: '/mute <player> [reason] [-d <duration>]'
    permission: cucumber.command.mute

  unmute:
    description: 'Unmute a player'
    usage: '/unmute <player> [reason]'
    permission: cucumber.command.unmute

  ban:
    description: 'Ban a player by unique identification (XUID)'
    usage: '/ban <player> [reason] [-d <duration>]'
    permission: cucumber.command.ban

  pardon:
    description: 'Pardons a player (undoes a /ban)'
    usage: '/pardon <player> [reason]'
    permission: cucumber.command.pardon

  uban:
    description: 'Perform a /ban on a player and ban their IP'
     usage: '/uban <player|-i <ip>> [reason] [-d <duration>]'
    permission: cucumber.command.uban

  upardon:
    description: 'Pardons a player and their IP (undoes a /uban)':
    usage: '/upardon <player|-i <ip>> [reason]'
    permission: cucumber.command.upardon

permissions:
  cucumber.command.rawtell:
    description: 'Allows for the use of /rawtell'
    default: op

  cucumber.command.log:
    description: 'Allows for the use of /log'
    default: op

  cucumber.command.alert:
    description: 'Allows for the use of /alert'
    default: op

  cucumber.mute:
    description: 'Mute-related commands'
    default: op
    children:
      cucumber.command.mute:
        description: 'Allows for the use of /mute'
        default: op
      cucumber.command.unmute:
        description: 'Allows for the use of /unmute'
        default: op

  cucumber.uban:
    cucumber.command.uban:
      description: 'Allows for the use of /uban'
      default: op
      children:
        cucumber.command.ban:
          description: 'Allows for the use of /ban'
          default: op
    cucumber.command.upardon:
      description: 'Allows for the use of /upardon'
      default: op
      children:
        cucumber.command.pardon:
          description: 'Allows for the use of /pardon'
          default: op